name: "Diff"
port: ":9050"
env: "local"
debug: true
log_level: "info"
telegram:
  bot_api_key: "key"
  chat_id: 1111
kucoin:
  spot_api_base_url: "https://api.kucoin.com"
  future_api_base_url: "https://api-futures.kucoin.com"
  refresh_connection_minutes: 10
  spot_max_subscriptions: 30
  future_max_subscriptions: 30
  top_change_limit: 100
mexc:
  spot_api_base_url: "https://api.mexc.com"
  future_api_base_url: "https://contract.mexc.com"
  ws_future_base_url: "wss://contract.mexc.com/edge"
  ws_spot_base_url: "wss://wbs.mexc.com/ws"
  refresh_connection_minutes: 10
  spot_max_subscriptions: 30
  future_max_subscriptions: 30
  top_change_limit: 100
  future_top_change_limit: 100
okx:
  ws_future_base_url: "wss://ws.okx.com:8443/ws/v5/public"
  refresh_connection_minutes: 10
  spot_max_subscriptions: 30
  future_max_subscriptions: 30
binance:
  spot_api_base_url: "https://api.binance.com"
  ws_spot_base_url: "wss://stream.binance.com:9443/ws"
  ws_future_base_url: "wss://fstream.binance.com/ws"
  refresh_connection_minutes: 10
  spot_max_subscriptions: 30
  future_max_subscriptions: 30
  top_change_limit: 100
bybit:
  spot_api_base_url: "https://api.bybit.com"
  ws_future_base_url: "wss://stream.bybit.com/v5/public/linear"
  ws_spot_base_url: "wss://stream.bybit.com/v5/public/spot"
  refresh_connection_minutes: 10
  # spot max 10
  spot_max_subscriptions: 10
  # unlimit future
  future_max_subscriptions: 10
  top_change_limit: 100
gate:
  spot_api_base_url: "https://api.gateio.ws/api/v4"
  ws_future_base_url: "wss://fx-ws.gateio.ws/v4/ws/usdt"
  ws_spot_base_url: "wss://api.gateio.ws/ws/v4/"
  refresh_connection_minutes: 10
  spot_max_subscriptions: 30
  future_max_subscriptions: 30
  top_change_limit: 100