FROM golang:1.21

RUN apt-get update && apt-get install -y --no-install-recommends curl make git unzip tzdata
RUN GO111MODULE=on 
RUN go install github.com/cortesi/modd/cmd/modd@latest

RUN mkdir -p /src/app
WORKDIR /src/app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .